### ISSUE TITLE
pb2nc PREPBUFR_MODEL_DIR_NAME conf variable.

### ISSUE THREAD

**Issue by jimfrimel** [NCAR/METplus#102]
Request: 
Remove PREPBUFR_MODEL_DIR_NAME conf variable.

PREPBUFR_DATA_DIR and PREPBUFR_MODEL_DIR_NAME are combined to be the directory that defines the input location of the prepbufr data.

Instead: Use Only PREPBUFR_DATA_DIR variable to define the prepbufr input directory.

**Comment by georgemccabe** [comment]
PREPBUFR_MODEL_DIR_NAME and PREPBUFR_DATA_DIR have both been removed. Users will now set PB2NC_INPUT_DIR and the model dir name must be specified in this path.
