### ISSUE TITLE
pb2nc prepbufr data dir exception

### ISSUE THREAD

**Issue by jimfrimel** [NCAR/METplus#103]
Bug:
Exception occurs when the defined PREPBUFR_DATA_DIR is the parent directory of the prepbufr data.

Currently, the path must be one level above the parent directory of the prepbufr data.
Add support so PREPBUFR_DATA_DIR can be defined as the parent directory of the data.

Explained:
ie. lets say this is the structure of our prepbufr path and data files on disk.

 .../blahdir1/blahdir2/blahdir3/<prepbufr_data files>

IF ... in the conf you define either of the following ...
that is, the last path element to be the parent of the data files,
you get an exception ...

PREPBUFR_DATA_DIR = .../blahdir1/blahdir2/blahdir3
PREPBUFR_MODEL_DIR_NAME =

OR ...
PREPBUFR_DATA_DIR = .../blahdir1/blahdir2
PREPBUFR_MODEL_DIR_NAME = blahdir3

The Exception....
CRITICAL: master_metplus  failed:
...
  File "/mnt/lfs1/projects/dtc-hurr/James.T.Frimel/metplus/metplus.hrrre/ush/pb2nc_wrapper.py", line 522, in retrieve_pb_time_info
    if len(date) == 8:
TypeError: object of type 'NoneType' has no len()

* Note: in the future, PREPBUFR_MODEL_DIR_NAME may be deprecated.

**Comment by georgemccabe** [comment]
This issue should be resolved with the pb2nc refactor.
