### ISSUE TITLE
Enhance string template substitution logic to specify width of forecast hours.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METplus#107]
This feature is needed to support the file naming conventions that arose during Perry Shafran's point verification efforts with METplus.

Currently, string_template_substitution.py has the following logic when formatting the "Level" or "Lead" values:
%HH means a 2-digit hour.
%HHH means a 3-digit hour.

Enhance the code to support the two new variants:
(1) %H means an unpadded integer value.  For example, a value of 1 is formatted as "1", 12 as "12", and 128 as "128".
(2) %.nH means a integer value padded with 0's out to a width of n.  For example, when format = "%.3H", a value of 1 is formatted as "001", 12 as "012", and 128 as "128".

This issue was discussed during the METplus meeting on 8/23/18.  Note that we also considered a more pythonic way of specified field width using "%H:03d" would mean to pad with 0's to a width of 3.  Similarly, "%H:X3d" would mean to pad with 'X' to a width of 3.  However, we decided that the NOAA scientists would be more comfortable using the printf formatting option.

Dan A also brought up f-strings, which are a newly supported string formatting option for python 3.  We should look into f-strings to make sure that we won't regret later what we implement now.

Note that we should also enhance string template substitution to support sub-hourly forecast intervals.  The MET software is set up to parse forecast times down to the second.  Forecast times are specified as "HH" for hours or "HHMMSS" for hours, minutes, and seconds.  For consistency, we should have METplus support similar logic.

**Comment by georgemccabe** [comment]
I believe I completed this work. Is there anything outstanding that needs to be done? We don't have support for minutes and seconds in a forecast lead. Is that in another ticket? It would be good to write some unit tests to ensure that everything works properly.

**Comment by georgemccabe** [comment]
Correction: I did actually write pytests to cover those cases. However, I tried running the tests and 5 other tests unrelated to these tests failed..

**Comment by georgemccabe** [comment]
The tests that failed are now skipped until Minna has a chance to resolve the changes. Closing issue.
