### ISSUE TITLE
Allow minutes and seconds in forecast lead template extraction

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/METplus#109]
I implemented a greedy method of handling %H (variable length forecast hour) that will search for digits until it finds a non digit character. However, this will have to be changed when we implement handling for %M and %S in forecast lead. It is important to remember that it was implemented this way because it will break the new functionality if it is not changed.

See src/basic/vx_cal/time_strings.cc in the MET code base for reference how to handle splitting up HHMMSS.

**Comment by georgemccabe** [comment]
Forecast lead templates are now designed to handle %H, %M, and %S. However, this functionality has not been thoroughly tested.

**Comment by bikegeek** [comment]
Related to  #275 

No current use case to support 90min = 1 hour 30 minutes
