### ISSUE TITLE
Enhance METplus file name template to handle NDAS time offsets

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METplus#11]
The NAM data assimilation system is cycled every 6 hours. During each cycle multiple PrepBufr point observation files are produced. And this process produces multiple files that are both valid at the same time. When choosing between two files with a common valid time, it's preferable to use the "later" one since it will contain more observations and have a higher level of quality control.

This logic is described further on this wiki page (search for "Notes on NDAS"):
   https://wiki.ucar.edu/display/DTC/NCEP+Data+Retrieval+via+Zeus

Here's an example of NDAS data:
   ftp://ftpprd.ncep.noaa.gov/pub/data/nccf/com/nam/prod/ndas.20160818

The directory "20160818" defines the date.
The prepbufr files are named: ndas.tHHz.prepbufr.tmNN.nr,
   where HH is 00, 06, 12, or 18
   and NN is 03, 06, 09, or 12

YYYYMMDD + HH specifies the data assimilation run time.
But NN specifies the number of offset hours.

So the valid time = YYYYMMDD + HH - NN

To test this, pull down some sample files and run the MET "pbtime" development utility to list the center time for the PrepBufr file.

So NN = 09 or 12 is preferable but 03 or 06 should be used if the preferable file is missing.

This task is to implement this logic into the MET+ file name template.

**Comment by georgemccabe** [comment]
These files are currently supported in METplus. Closing this ticket.
