### ISSUE TITLE
pb2nc_wrapper.py support different input file formats

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#110]
Similar to what is being supported for the point_stat_wrapper.py, process the input file via the filename template rather than the regex_pattern.  This will support input files that don't have to follow a specific ordering of YMD valid/init time, lead/fcst, cycle and offset order.

e.g. 20170811.gfs.t03z.f12.tm00.nc
       gfs.t03z.f12.tm00.20170811.nc

both of these formats should be supported and correctly identify the YMD date, cycle, offset, and forecast hours.

**Comment by georgemccabe** [comment]
Changes to StringSub should handle these file formats.
