### ISSUE TITLE
Update the way thresholds are specified in METplus config files from numbers to threshold strings.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METplus#118]
Thresholds in the METplus config files are currently defined as numeric, assuming that they are all type greater-than.  Instead, define these thresholds as strings and pass them directly to the MET config files.

Ideally, METplus would validate these strings.  They all begin with one of...
>,>=,==,!=,<,<=,gt,ge,eq,ne,lt,le ... and be followed by a number

They can also be more complex: >=25&&<35 ... or ... ==1||==2||==3

**Comment by georgemccabe** [comment]
This has been completed. Each list item will be checked to ensure that it starts with a comparison operator. This could be enhanced to ensure that the only characters that are found in the list are valid (i.e. comparison operator, number, &, |, etc.)
