### ISSUE TITLE
prepend process/tool name to keywords used in METplus config files

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#120]
In the METplus config files there are some keywords that can be used by one or more processes/MET tools in that METplus use case config file.  Prepend the MET tool name to the keyword:
e.g.  /full/path/to/{TOOL_NAME}_CONFIG_FILE

**Comment by georgemccabe** [comment]
I renamed a few variables that are specific to pcp_combine to include PCP_COMBINE in the name.

**Comment by georgemccabe** [comment]
I have not yet updated the documentation to include these

**Comment by georgemccabe** [comment]
Documentation was updated to include all <app_name>_CONFIG_FILE variables.
