### ISSUE TITLE
Migrate MET config files from PARM_BASE/met_config to the use case directory

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#123]
In an effort to keep the relevant MET config files grouped with their use cases, move the MET config files currently located in the PARM_BASE/met_config directory to their corresponding <use_case>/met_config directory.

**Comment by georgemccabe** [comment]
Should the masks go in <use_case>/met_config/mask?

**Comment by bikegeek** [comment]
That makes sense to me, but the rest of the group may want to weigh in on this...

**Comment by malloryprow** [comment]
I think that makes sense.
