### ISSUE TITLE
Create a utility function to handle the non-MET executables

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#126]
Write a utility function that reads the config file for the non-MET executables which can be populated into the METplus wrapper's dictionary that contains the key-values in the configuration file.

**Comment by georgemccabe** [comment]
I created a utility function called add_common_items_to_dictionary. It takes the conf object and a dictionary as inputs. It adds all of the non-MET exes to the dictionary from the conf. It is in met_util.py. I added a pytest for the function as well.
