### ISSUE TITLE
Replace getdir('exe') in METplus config files with getexe 

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#127]
In some METplus config files, getdir('/path/to/exe') is used to retrieve the non-MET executables instead of getexe().

**Comment by jimfrimel** [comment]
The getdir function is an alias function and searches the dir section of a conf file.
 It only requires a single argument. Passing in additional arguments
has a different meaning.  Calling getdir('exe','SOMEVAR') is incorrect and will return 
the value 'SOMEVAR'.  Consult the API.

This has been fixed ...
Only two files required changes
    ush/pb2nc_wrapper.py
    ush/point_stat_wrapper.py

Also for consistency, the calls in the above files that were 
using getstr('dir','SOMEVAR') where changed to used the function getdir('SOMEVAR')
