### ISSUE TITLE
Compare gridded wrappers should process all fields in a single run

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/METplus#136]
Currently these wrappers will loop over the list of fields and process them individually with their own run of the MET app (i.e. grid_stat). It would be more efficient to pass all of the fields to process to one instance of the MET app.

Q: Do we want to support the current method where each field gets its own run of grid_stat? Or do we always want to put all fields from the list into a single run?

**Comment by JohnHalleyGotway** [comment]
George,

Jim and I were talking about this yesterday as it relates to ensemble_stat.

In the past, we have typically run Grid-Stat once to process many variables
in a single run.

Splitting it up into multiple runs was really driven by what data lives in
what files.  For example, if evaluating model A, you may run Grid-Stat once
to compare the model's temperature and winds to URMA... and run it a second
time to compare the model's precip to StageIV precip analysis.

So we often run Grid-Stat to compare multiple fields at once.

BUT when running MODE, you'd only evaluate one field at a time.  MODE can
only process a single field at a time.

Confused yet?

John

**Comment by georgemccabe** [comment]
So it sounds like we need to support both the current version (process 1 field at a time) and also be able to process all fields at once. MODE will always use the current method, while grid_stat can chose but will default to the new method. How will ensemble_stat be able to run? Both ways?

**Comment by JohnHalleyGotway** [comment]
Yes...
   grid_stat, point_stat, ensemble_stat, and wavelet_stat can all process
multiple fields in a single run.
   mode, mtd, and series_analysis can only process a single field in each
run.

John

**Comment by georgemccabe** [comment]
OK, so it sounds like we may want a subclass for grid/point/ensemble/wavelet_stat and another one for mode, mtd, series_analysis. They could likely both inherit for another class that contains code that is relevant to all 7.

**Comment by georgemccabe** [comment]
After talking with John, it looks like we will need an option to specify if we are going to run these apps on all fields at once or run it once per field. pcp_combine will create a separate file for each accumulation interval. This means that we cannot run grid_stat or any other related app on all field/level combinations since they will be different files. The default behavior should be process all fields, but precip accumulation use cases will have a conf to make sure it processes each field separately.

**Comment by georgemccabe** [comment]
There is now a boolean conf item called GRID_STAT_ONCE_PER_FIELD. The default value is False, so all field/level combos will be added to a single call to grid_stat for a given time. This is the typical behavior. You should set it to True when processing precip accumulations because each level specifies an accumulation and different accumulations can have different input files to grid_stat. This behavior can be added to ensemble_stat and other wrappers.

**Comment by georgemccabe** [comment]
The changes are checked into GitHub in the branch feature_136_gridstat_mode_diffs. We need to test all of the grid_to_grid use cases to ensure they still run properly with these changes. I will keep this ticket open until we test the changes and merge into develop.

**Comment by georgemccabe** [comment]
QPF examples were tested and ran properly. Mallory tested the grid_to_grid examples and they ran correctly as well. Merged changed into develop branch and closing issue.
