### ISSUE TITLE
Documentation for Use Cases

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#137]
Create documentation that is complimentary to any existing Doxygen documentation for each supported use case.  Complimentary documentation should not be as technically detailed as the Doxygen documentation but should provide a scientist/user a good understanding of the use case.  In addition, prepare a description/definition of use case.  

The documentation should either reside in it's own document, or be included in the METplus User's documentation- the location needs to be determined by the team.

**Comment by bikegeek** [comment]
Refer to Github Issue #254 (README template)

**Comment by georgemccabe** [comment]
I believe this work is done when we created the 3.0 release with Sphinx Gallery documentation for each use case.
