### ISSUE TITLE
Bring METplus MET config files up to date with MET 8.1 config files

### ISSUE THREAD

**Issue by jimfrimel** [NCAR/METplus#138]
Bring the METplus MET met_config files under the METplus parm/use_cases directories
up to date and based off of their respective MET 8.0 version. 

MET 8.0 config file changes can be found with the distribution.
MET_INSTALL_DIR/share/met/config/README

**Comment by JohnHalleyGotway** [comment]
We should add back in the MET version number to the MET config files as a comment.

**Comment by georgemccabe** [comment]
Is there a list of the new MET config additions for 8.1? Do we just need to add the new items with the default values so the user can see what is available?

We will update each MET config file in the METplus wrappers repo (in the met_config directories) and add version = "8.1"; to the end of the config file to mark that we have updated that config file to match the latest release version. Is that correct?

**Comment by jprestop** [comment]
>
> Is there a list of the new MET config additions for 8.1?
>
I don't think so.

> Do we just need to add the new items with the default values so the user
> can see what is available?
>
Yes, I believe so.

> We will update each MET config file in the METplus wrappers repo (in the
> met_config directories) and add version = "8.1"; to the end of the config
> file to mark that we have updated that config file to match the latest
> release version. Is that correct?
>
Yes, but I think we want to leave it commented out.

Julie

**Comment by georgemccabe** [comment]
Thanks for the reminder that it should be commented out.

Should we refer to the met-8.1_beta2 release on dakota to see updated
config files?

**Comment by jprestop** [comment]
>
> Should we refer to the met-8.1_beta2 release on dakota to see updated
> config files?
>
I think that is likely the best way to proceed, keeping in mind that it is
a beta release and other changes could be made still.

Julie

**Comment by georgemccabe** [comment]
I am working on the qpf/met_config directory now.

**Comment by georgemccabe** [comment]
I have finished qpf, grid_to_grid, and ensemble configs. Working on grid_to_obs now...

**Comment by georgemccabe** [comment]
I have finished all of the MET config files in the repository. I added defaults that weren't listed, removed commented out lines that are necessary, and added a commented line with version = "V8.1"; to each file.
