### ISSUE TITLE
Reconcile var_list across all wrappers and call parse_var_list fewer times

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/METplus#143]
series by lead and series by init still use the old method of describing variables to be read in the conf files.
VAR_LIST = TMP/P850, HGT/P500
We should change this to use the FCST/OBS_VAR1_NAME, FCST/OBS_VAR1_LEVELS format so they are consistent with the other wrappers' config:

FCST_VAR1_NAME = TMP
FCST_VAR1_LEVELS = P850
FCST_VAR2_NAME = HGT
FCST_VAR2_LEVELS = P500

I am not sure if FCST or OBS is appropriate for these variables, but that is how the other wrappers are handled.

I also noticed that util.parse_var_list is being called once for each run time of each wrapper. This is not necessary. We can either have each wrapper that needs the var list to parse it when it is initialized, or we can parse it in master_metplus and pass in the list to each wrapper whether they need it or not.

**Comment by bikegeek** [comment]
Hi George,

If you want, you can make the changes in those wrappers since I’m off doing AF and GMTB tasking- if this needs to be done soon.  I have a few GitHub issues I’m trying to “wrap up” (no pun intended).  

If this can wait, I can make these changes.

Thanks,
Minna

**Comment by georgemccabe** [comment]
Hi Minna,
This is not an urgent fix, so it can wait until you have time. The functionality works fine, it would just be nice to reconcile differences between wrappers so we are consistent. I'll assign the issue to you.

**Comment by georgemccabe** [comment]
@bikegeek let me know when you complete this task. I want to move the call to parse_var_list so that it is not called for every wrapper for every run time. It will be easier to do this once all of the wrappers are using the var list in the same way. Again, no rush

**Comment by georgemccabe** [comment]
Some functionality still uses VAR_LIST instead of [FCST/OBS]_VAR[N]_NAME/LEVEL. 

feature_util.py
series_by_lead_wrapper.py
series_by_init_wrapper.py

**Comment by georgemccabe** [comment]
I noticed there are INIT_INCLUDE and INIT_EXCLUDE config variables in these wrappers. Is this something we want to support for all? If so, we should modify met_util.py loop_over_times_and_call() method to to check if the current runtime corresponds to the exclude value and skip it. I am not sure how INIT_INCLUDE is intended to work.

**Comment by bikegeek** [comment]
All wrappers have migrated to using the [FCST/OBS]_VAR[N]_NAME/LEVEL] since METplus v2.0.
This is no longer an issue.

**Comment by georgemccabe** [comment]
The wrappers I mentioned previously use VAR_LIST to describe variables in v2.1. Also, parse_var_list is still being called for every run time when it only needs to be called once. This work has not been completed.
feature_util.py:    var_list = util.getlist(cu.getstr('config', 'VAR_LIST'))
series_by_init_wrapper.py:        self.var_list = util.getlist(self.config.getstr('config', 'VAR_LIST'))
series_by_lead_wrapper.py:        self.var_list = util.getlist(self.config.getstr('config', 'VAR_LIST'))

**Comment by georgemccabe** [comment]
CommandBuilder now calls create_c_dict in the init function, so as long as a wrapper is calling the super init function, it will have access to self.c_dict which will contain an item called 'VAR_LIST' that contains a list of field information. This list is generated from met_util's parse_var_list function. Individual wrappers will no longer have to call this method to get this information -- fcst and obs (and sometimes ens) name, level thresh, and extra options.

Note: the files listed above still use the VAR_LIST config variable instead of parsing [FST/OBS]_VAR<n>_[NAME/LEVEL].

**Comment by georgemccabe** [comment]
Calls to met_util.parse_var_list was actually moved to be called more frequently instead of less so that these variables can utilize filename templates. The function will be called for each runtime/lead combination so it can read in the current timing information and substitute values.

We still need to remove uses of VAR_LIST then we can close this ticket.

**Comment by georgemccabe** [comment]
@bikegeek , are you able to get this done for the 3.0 release? It would be great to deprecate VAR_LIST before then.

**Comment by bikegeek** [comment]
George will work on the met_util.py parse_var_list() to support VARn_LEVEL, VARn_NAME and then I can incorporate any necessary changes to the feature_util.py: 
1) modify retrieve_and_regrid() to invoke parse_var_list() instead of feature_util.py's retrieve_var_info
2) make necessary changes to the feature_relative use case conf files
3) make necessary changes to the initialization and other sections in the series_by_init_wrapper.py and series_by_lead_wrapper.py

**Comment by bikegeek** [comment]
Modifications made to series_by_init_wrapper.py, series_by _lead_wrapper.py, feature_util.py, met_util.py (removal of unnecessary/no longer used function), feature_relative.conf, series_by_init_12-14_to_12-16.conf, series_by_lead_all_fhrs.conf, and series_by_lead_by_fhr_grouping.conf.

Changes committed to feature branch, then merged to the 'develop' branch.

**Comment by georgemccabe** [comment]
Made changes to met_util.py parse_var_list to require FCST and OBS vars be set, or BOTH can be used instead. Merged into develop.

**Comment by bikegeek** [comment]
ToDo:  In the series_by_init_wrapper.py and series_by_lead_wrapper.py, create another function that cleans out just the files in the users TMP directory, rather than deleting and re-creating a new TMP directory.

**Comment by bikegeek** [comment]
instead of doing the above, see GitHub Issue #341, which has been closed.

**Comment by bikegeek** [comment]
updated met_util.py check_for_deprecated_config() to check for VAR_LIST, EXTRACT_VAR_LIST, and SERIES_ANALYSIS_VAR_LIST

**Comment by georgemccabe** [comment]
@bikegeek 's comment reminded me that we should test the validate_config.py script to make sure it handles VAR_LIST correctly. Other config variables that include VAR_LIST in the name still exist, like PB2NC_OBS_BUFR_VAR_LIST. The script should only try to replace VAR_LIST if it is found at the beginning of a line or if it is surrounded by {}s meaning it is referenced in another config variable.

I also noticed there are FCST_[VAR/LEVEL]_LIST OBS_[VAR/LEVEL]_LIST in StatAnalysis and MakePlots wrappers. I am not familiar with those but they may be able to be replaced with [FCST/OBS]_VAR<n>_[NAME/LEVEL]

**Comment by georgemccabe** [comment]
I just looked at the deprecated variable list. If the variable cannot be simply renamed, you have to add 'copy': False to the dictionary for that item. Otherwise METplus will try to replace the value. I made the changes to fix this.

**Comment by georgemccabe** [comment]
Closing this ticket because I believe it is complete. Please reopen if there are other outstanding tasks related to this issue.
