### ISSUE TITLE
point_stat_wrapper isn't returning expected model files for a given prepBUFR file

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#145]
Perry Shafran is attempting to run the point_stat_wrapper on his data on WCOSS.  Some of the expected model files aren't getting produced.

**Comment by bikegeek** [comment]
sample data provided by Perry, downloaded from WCOSS host gyre onto RAL host Dakota:/d4/projects/METplus/nam_perry/obs/nam.20181114/nam.t06z.prepbufr.tm06.nr and /d4/projects/METplus/nam_perry/model/

and log file, metplus_final.conf and tarball of METplus source code, Metplus_perry.tar in /d4/projects/METplus/nam_perry/debug

**Comment by georgemccabe** [comment]
Tested that refactor to pb2nc and point_stat allows this case to work correctly.

The following config items need to be set for it to work:

[config]
LOOP_BY_INIT = False
VALID_TIME_FMT = %Y%m%d%H
VALID_BEG = 2018111400
VALID_END = 2018111400
VALID_INCREMENT = 21600

LEAD_SEQ = 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84

PB2NC_OFFSETS = 6, 5, 4, 3, 2, 1, 0

PB2NC_SKIP_IF_OUTPUT_EXISTS = True

[dir]
PB2NC_INPUT_DIR = /d3/projects/METplus/nam_perry/obs
PB2NC_OUTPUT_DIR = {OUTPUT_BASE}/nam/conus_sfc

FCST_POINT_STAT_INPUT_DIR = /d3/projects/METplus/nam_perry/model
OBS_POINT_STAT_INPUT_DIR = {PB2NC_OUTPUT_DIR}

POINT_STAT_OUTPUT_DIR = {OUTPUT_BASE}/nam/stat

[filename_templates]
PB2NC_INPUT_TEMPLATE = nam.{da_init?fmt=%Y%m%d}/nam.t{da_init?fmt=%2H}z.prepbufr.tm{offset?fmt=%2H}.nr

PB2NC_OUTPUT_TEMPLATE = nam.{valid?fmt=%Y%m%d}/nam.t{valid?fmt=%2H}z.prepbufr.nc

FCST_POINT_STAT_INPUT_TEMPLATE = nam.{init?fmt=%Y%m%d}/nam.t{init?fmt=%H}z.awphys{lead?fmt=%2H}.tm00.grib2

OBS_POINT_STAT_INPUT_TEMPLATE = {PB2NC_OUTPUT_TEMPLATE}
