### ISSUE TITLE
Include version number somewhere with METplus releases

### ISSUE THREAD

**Issue by NYColoraDan** [NCAR/METplus#167]
When downloading a release of METplus, one can use the command line or download the release from the releases tab on github.com. When using the command line and creating a local branch using the release tag, it detaches the repository from the github remote repository and no git commands work to see what tag was used during the "git clone" command. Thus, the user has no way to know what tag they grabbed and therefore which version of METplus they are using.

When downloading the release from the github releases tab, the release version is in the tarball name, but if they remove the tarball none of the source of METplus contains any information about the version number that I am aware of.

Suggestions:
1. When running master_metplus.py -h, show the version number to the user
2. Include the version number as a conf item printed out in metplus_final.conf like METPLUS_VERSION

**Comment by georgemccabe** [comment]
The version is currently stored in a text file (doc/version). It just holds the current version number (2.0.3). When you run master_metplus.py -h the version will be displayed with the current command run, i.e.:

01/25 19:38:29.772 master_metplus (master_metplus.py:69) INFO: METplus v2.0.3 called with command: /d1/mccabe/METplus/ush/master_metplus.py -h

It is also output as the first line in the log output file for clarity:

01/25 18:47:45.058 metplus (master_metplus.py:88) INFO: Running METplus version 2.0.3

It is also added to the final conf as METPLUS_VERSION

There are instructions to update the version file in notes for creating a release on the wiki.
