### ISSUE TITLE
in series_by_lead_wrapper.py, update FHR_INC to LEAD_SEQ (not FHR_INCREMENT)

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#175]
In the series_by_lead_wrapper.py script, INIT_INC was replaced by INIT_INCREMENT to explicitly differentiate from INIT_INC (for init INCLUDE) in other MET tools.  For consistency, the same needs to be done for VALID_INC.  This should be updated to VALID_INCREMENT to remove any confusion.

**Comment by georgemccabe** [comment]
I just add functionality to specify start, end, and increment of a list in the LEAD_SEQ config file. Instead of:

LEAD_SEQ = 3, 5, 7, 9

you can now write

LEAD_SEQ = list(3,9,2)

We can change the name from 'list' if we'd like. This functionality currently differs from the python function range in that the end value is included in the list generated by 'list' instead of excluded.

**Comment by georgemccabe** [comment]
I propose the following changes to conform to the naming conventions of the other wrappers:

Add a boolean METplus config variable called SERIES_BY_LEAD_GROUP or something similar. If it is set to false, we don't group the forecasts and we read the forecast list as

SERIES_BY_LEAD_GROUP = False
LEAD_SEQ = list(0,96,6)

This replaces the case where:
FHR_BEG = 0
FHR_END = 96
FHR_INCREMENT = 6
and the FHR_GROUP_BEG, FHR_GROUP_END, FHR_GROUP_LABELS variables are not set.

If SERIES_BY_LEAD_GROUP is True, we use LEAD_SEQ_[N] and LEAD_SEQ_[N]_LABEL to specify the forecast group lists.

SERIES_BY_LEAD_GROUP = True
LEAD_SEQ_1 = list(0,18,6)
LEAD_SEQ_1_LABEL = Day1
LEAD_SEQ_2 = list(24,42,6)
LEAD_SEQ_2_LABEL = Day2
LEAD_SEQ_3 = list(48,66,6)
LEAD_SEQ_3_LABEL = Day3
LEAD_SEQ_4 = list(72,72,6)
LEAD_SEQ_4_LABEL = Day4

will replace:

...
FHR_INCREMENT = 6
FHR_GROUP_BEG =  0, 24, 48, 72
FHR_GROUP_END = 18, 42, 66, 72
FHR_GROUP_LABELS = Day1, Day2, Day3, Day4

Please let me know if this sounds good or if you have any suggestions.

**Comment by bikegeek** [comment]
I don't see why this shouldn't work.  Thanks for looking into this.

-Minna
---------------
Minna Win
NCAR
Research Applications Lab
Phone: 303-497-8423
Fax:   303-497-8401

**Comment by georgemccabe** [comment]
This functionality has been implemented and added to the develop branch. Leaving this issue open until the documentation has been updated to reflect the changes.

**Comment by georgemccabe** [comment]
New section in documentation called Common Config Variables describes this functionality. Closing.
