### ISSUE TITLE
Feature relative sample data tarball reorganizing

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#176]
The current directory structure for the feature relative sample data mirrors the file structure of SBU (Stony Brook University), the source of the data.  In creating the METplus tutorial, it is customary to name the top level directory consistent with the name of the use case/lesson.  

Rename and if necessary, reorganize the data to be consistent with the METplus tutorial material and update any METplus configuration files that use these sample data.

**Comment by georgemccabe** [comment]
The sample_data-cyclone_track_feature.tgz tarball now contains cyclone_track_feature as the top level directory. The structure is the same under that. I updated config files that reference these data to expect this naming convention.
