### ISSUE TITLE
Remove instructions for MET 6.0 in metplus_system.conf

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#182]
During the latest METplus in-house tutorial,  an attendee noticed instructions for MET6.0 and was confused as to whether we are supporting MET6.0.  We need to remove the instructions for setting the variables for MET6.0 as METplus is now "matching" MET releases (ie MET 8.0 w/ METplus 2.0, MET 8.1 w/METplus 2.1, etc.)

**Comment by jimfrimel** [comment]
Removing MET6.X references in metplus_system.conf
"METplus scripts" no longer support MET6.x

For reference: The following comments were removed from metplus_system.conf
`# Note:
# Variables and MET versions required by the MET plot_tcmpr.R script.
# This note is highlighting the MET R script requirements.
# For MET 6.0, MET_BUILD_BASE and RSCRIPTS_BASE, MUST have the same
# parent directory tree, else plot_tcmpr.R will error.
# Note: MET may require adding netcdf/lib to your LD_LIBRARY_PATH
#       LD_LIBRARY_PATH=/usr/local/netcdf/lib:${LD_LIBRARY_PATH}
#
# MET 6.1 and later: MET_INSTALL_DIR, MET_BASE
# MET 6.0: MET_BUILD_BASE, RSCRIPTS_BASE

# MET_BUILD_BASE, and RSCRIPTS_BASE are only need for backward
# compatibility when running METplus tcmpr_plotter_wrapper.py with 
# MET 6.0 or earlier plot_tcmpr.R scripts.
#MET_BUILD_BASE = /path/to
#RSCRIPTS_BASE = {MET_BUILD_BASE}/scripts/Rscripts
`

**Comment by jimfrimel** [comment]
See commit hash 2bec4151f1d8f
