### ISSUE TITLE
Refactor extract_tiles to support different input data directory structures

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#199]
In running the feature_relative use case for the MERIT project, it has become clear that the extract_tiles wrapper is looking for input data that is separated by subdirectories defined by initialization time.  This is how the SBU input data is organized.  The track data for MERIT all resides under one directory and that directory does not necessarily contain any date information.  Allow the user to define whether their data is organized into dated subdirectories or not.  The current implementation forces users to re-organize their data into directories that might not make sense for their application.

Proposed solution:  introduce new configuration parameter to indicate how the input track data is organized: e.g. INPUT_DIR_BY_INIT , INPUT_DIR_BY_OTHER 

If INPUT_DIR_BY_INIT is True, proceed as usual and re-create the initialization time from the INIT_BEG and INIT_END and append the init YYYYMM to the track input directory.

If INPUT_DIR_BY_OTHER is True, proceed to search the directory with format specified in the filename template 

Confer with Tracy and see if she has any preferences and if she knows of any other directory structures which will need to be considered.

**Comment by georgemccabe** [comment]
I ran into a similar issue with pcp_combine and I was able to resolve it by
utilizing the string template with or without a dated subdirectory and
removed the code that relied on the data being in dated subdirectories. I
am not too familiar with the dataset, but could you do something like this?
I have also used os.walk to traverse recursively through sub directories to
find files.

**Comment by bikegeek** [comment]
Thanks George.  I think I might try that first before introducing new keys
in the config file.  I don't know when I will get around to it, since I'm
now doing METviewer/METexpress stuff.  Multi-tasking really sucks!

-M
---------------
Minna Win
NCAR
Research Applications Lab
Phone: 303-497-8423
Fax:   303-497-8401

**Comment by bikegeek** [comment]
bummer! I tried using met_util's get_files but it really is the directory
where the files reside that I need.  The extract_tiles_wrapper invokes
tc_stat and the tc_stat tool has a -lookin flag which requires the
directory!  Have you encountered something like this?  It looks like I need
to get the directory where these files reside- I think I can modify
something in met_util.py to do this...

Thanks for your help

-Minna


---------------
Minna Win
NCAR
Research Applications Lab
Phone: 303-497-8423
Fax:   303-497-8401

**Comment by georgemccabe** [comment]
Are you saying that you need to set -lookin to {TC_STAT_INPUT_DIR}/YYYMM?
If so, could you set the TC_STAT_INPUT_TEMPLATE to {valid?fmt=%Y%m} or
something like that and set the -lookin value that way?

**Comment by bikegeek** [comment]
The only glitch is that when the extract_tiles_wrapper is invoking tc_stat,
it does so without a tc_stat config file or tc_stat related configs, but I
could set up the feature relative config file with a TC_STAT_INPUT_DIR and
set that to the tc_pairs output directory....

Thanks,
Minna
---------------
Minna Win
NCAR
Research Applications Lab
Phone: 303-497-8423
Fax:   303-497-8401

**Comment by bikegeek** [comment]
Hi George,

It turns out that it's easier to just get the list of all the .tcst files
and pass those into -lookin.  I was talking to John about this issue and
that looks like the easiest fix that will support any unconventional
directory structures.

Thanks for your help!
---------------
Minna Win
NCAR
Research Applications Lab
Phone: 303-497-8423
Fax:   303-497-8401

**Comment by bikegeek** [comment]
Now generating a list of tcst files (.tcst extension included in filename, path included) and passing this to the tc_stat_wrapper, which in turn is sending this list to the MET tc_stat tool via -lookin. 
Tested by running original code, then comparing output via ncdiff.  emailed Tracy that this update is now available in the 'develop' branch.

**Comment by georgemccabe** [comment]
Can -lookin access a text file with a list of filenames? Other MET tools support this and there is a METplus utility to handle the writing of this file in the staging dir. The function is in compare_gridded_wrappers.py and is called write_list_file. It takes a filename and a list of files and it writes the filename under STAGING_DIR/file_lists. This would be a much cleaner approach than having hundreds of files passed in on the command line.

If you want to use this function to accomplish this, you can move it up from compare_gridded_wrapper.py to command_builder.py so that it can be used by all wrappers.

**Comment by bikegeek** [comment]
-lookin can read in a directory or list of files.  According to John, it is
actually more efficient to pass in a list of files.  These are passed in as
a string consisting of file names.

-Minna
---------------
Minna Win
NCAR
Research Applications Lab
Phone: 303-497-8423
Fax:   303-497-8401
