### ISSUE TITLE
Track and intensity is inconsistent with the NHC ATCF data 

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#213]
When running the track and intensity example using the track_and_intensity_ATCF.conf file, when the top level directory is preferred over the matching of pairs by the tc_stat_wrapper- the results are inconsistent.  The MET tool finds matches whilst the tc_stat_wrapper pairs do not result in "matches".  In addition, the tcmpr plotter does not recognize the sole .tcst file generated by the MET tool when the top level directory is passed to MET tc_pairs (vs. paired input files found by tc_stat_wrapper.py).

**Comment by bikegeek** [comment]
This is an issue encountered with the NHC ATCF data.  When running the tc_pairs_wrapper with the SBU (non-ATCF) data and calling MET tc_pairs with top-level directory names and the ADeck/BDeck pairs from the wrapper, the results are consistent.

**Comment by bikegeek** [comment]
The logic used to find matching ADeck/BDeck files within a time window does not work when the format of the init time is YYYYMMdd_HH but the date in the file is YYYY.  The matching process takes an extremely long time to find matches, and the matched ADeck/BDeck pairs, when submitted to the MET tc_pairs tool, does NOT produce results.

**Comment by bikegeek** [comment]
This will be fixed with the refactoring of the TC-Pairs Wrapper, which is being refactored by George McCabe.

**Comment by georgemccabe** [comment]
Thanks for updating this ticket, @bikegeek . To clarify, is the issue that we get different results when running track_and_intensity_ATCF.conf with top level dirs set compared to top level dirs not set?

**Comment by bikegeek** [comment]
Correct.  This is because the initial implementation for ATCF formatted
input was incorrect.  Your refactor should rectify this incorrect behavior.


---------------
Minna Win
NCAR
Research Applications Lab
Phone: 303-497-8423
Fax:   303-497-8401

**Comment by georgemccabe** [comment]
Moved to 3.0 release from bugfix release because we decided it doesn't warranta  bugfix release.

**Comment by georgemccabe** [comment]
Refactor now correctly finds relevant files within the wrapper to process with tc_pairs. Updated config files and documentation to reflect new config variable names. Tested use cases that run TcPairs to ensure they run correctly.
