### ISSUE TITLE
Inconsistencies between wrapper variables

### ISSUE THREAD

**Issue by CPKalb** [NCAR/METplus#217]
The "model" labels in the met_config files are inconsistent among different wrappers.  For example, in the point_stat-wrapper, it's called MODEL_NAME, in the grid_stat_wrapper it's called MODEL_TYPE, and in the ensemble_stat_wrapper it's MODEL.  Would it be worth making these consistent across different wrappers?

**Comment by georgemccabe** [comment]
Yes, it is definitely worth making them consistent. Thank you for creating a ticket for this. Please create tickets for any other inconsistencies you notice!

**Comment by bikegeek** [comment]
In the MET point-stat default config file, MODEL is used so it makes sense to change MODEL_NAME to MODEL for the METplus point_stat_wrapper.

**Comment by georgemccabe** [comment]
In the grid_stat config file (and others I believe), the environment variable is also called ${MODEL}. The corresponding METplus config variable is called MODEL_TYPE. Should we change it across the board so that METplus and MET config files both use MODEL? That seems good to me.

**Comment by georgemccabe** [comment]
MET config files use OBTYPE while METplus config files use OB_TYPE. Should these both be OBTYPE?

**Comment by georgemccabe** [comment]
OB_TYPE is now OBTYPE and MODEL_TYPE or MODEL_NAME is now MODEL
