### ISSUE TITLE
Clean up wrapper variable names and associated config files

### ISSUE THREAD

**Issue by malloryprow** [NCAR/METplus#219]
Work on ...

- work on renaming variables to contain the wrapper specific name (prepend wrapper name to the variable names, ex. VERIF_GRID to MAKE_PLOTS_VERIF_GRID) and update associated documentation
- work on following coding standards (Mallory needs to do this)

**Comment by malloryprow** [comment]
Associated with issue #217 cleanup?

**Comment by malloryprow** [comment]
Should probably change *_OUT_DIR to be *_OUTPUT_DIR to be consistent with *_INPUT_DIR.

**Comment by georgemccabe** [comment]
I just did a replace for all instances of _OUT_DIR to be _OUTPUT_DIR for all wrappers.

**Comment by malloryprow** [comment]
Sweet, thanks @georgemccabe!

**Comment by georgemccabe** [comment]
Moving this to the 2.1 bugfix milestone

**Comment by georgemccabe** [comment]
@malloryprow  any update on the status of this work? Do you need help getting it done before the 3.0 release?

**Comment by malloryprow** [comment]
stat_analysis_wrapper.py and make_plots_wrapper.py will be renamed config variables and cleaned up when feature_226_stat_analysis_cleanup gets into develop.

**Comment by bikegeek** [comment]
DUPLICATE.
Closing, this is the predecessor to GitHub Issue #306 but #306 specifically identifies which changes need to be made
