### ISSUE TITLE
Fix TCMPRWrapper config

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#220]
The TCMPR_DATA variable should be renamed TCMPR_DATA_DIR and moved from the [config] section to the [dir] header.  Concomitantly make the necessary change to the tcmp_plotter_wrapper.py code

**Comment by jimfrimel** [comment]
Added INIT_TIME_FMT = %Y%m%d to cyclone_plotter.conf

Changed conf variable from TCMPR_DATA to TCMPR_DATA_DIR 
Confirmed, Variable already resided in all [dir] sections.

Update conf variable name in lyx documentation 
    - did not rebuild any of the pdf files.

Re-ran track and intensity and cyclone plotter functional tests.

Changes committed to develop branch: commit hash 63ac62799d35

Deleted this feature branch: feature_220_fix_tcmpr_config
