### ISSUE TITLE
Make the input model configurable for METplus

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METplus#23]
Currently only GFS is supported in constants.pdef.

Add new variable named "MODEL" (i.e. GFS, ECMWF, NAM).  For each model, the code will require that the following variables be defined:
   {MODEL}_FCST_FILE_TMPL
   ...

Add comments to constants.pdef to tell users what to do.  Remove hard-coded references to GFS from the code.

**Comment by georgemccabe** [comment]
This has been completed. We are currently using the FCST_* convention for defining information about model data.
