### ISSUE TITLE
Handle zero valued increment values set by user

### ISSUE THREAD

**Issue by bikegeek** [NCAR/METplus#30]
in debugging for SBU, if the user attempts to set the increment to 0 in the constants_pdef.py for the FHR_INC, a python error is raised: ValueError in series_by_lead.  Either check for this, make a note in the configuration file that xxx_INC must be greater than 0, logs the Python exception.  Or alternately, we can allow this and use a different construct to handle such cases.

Do this in all modules: run_tc_pairs, extract_tiles, series_by_lead and series_by_init.

**Comment by georgemccabe** [comment]
master_metplus.py has a check to ensure that the increment is at least 60. We only support time precision up to minutes, so any increment lower than that will not change the time value and cause an infinite loop.
