### ISSUE TITLE
Generalize reading of track_data directory structure

### ISSUE THREAD

**Issue by TaraJensen** [NCAR/METplus#34]
It appears that tc_pairs.py expects a very specific directory structure for track data to include YYYYMM.  While writing this, it struck me that you might be able to specify that structure in the path designation in constants_pdef.py (SBU-alpha version) and metplus.conf (EMC-alpha version).  

If YYYYMM or some other variable path can't be specified, then it would be good to generalize the track reader utility to allow for a flexible path definition.

**Comment by bikegeek** [comment]
This is now related to Agile Task #47725 with the exception that a new configuration framework is being employed (from HWRF produtil) and constants_pdef.py and the constants_pdef configuration file are no longer in use.  

Proposed refactor:  in the appropriate use case configuration file, the user indicates the full filepath of the track data in the [filename_templates] section. The date and filename can be extracted to retrieve the data files that are within the specified time window (specified in the use case or some other MET+ configuration file).
