### ISSUE TITLE
Pulling time information from a filepath and template

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/METplus#36]
We currently have functionality to produce a filepath given a template and time information 
 like valid/init/forecast/accum (Thanks, Julie!). We don't currently have any utilities to get time information out of a filepath and template. For example, if we have the template:

NATIONAL_BLEND_INPUT_TEMPLATE = {valid?fmt=%Y%m%d}/blendp_qpf_{valid?fmt=%Y%m%d%H}.grd

and the filepath:

20170718/blendp_qpf_2017071806.grd

we could use that to pull out time information like %Y%m%d%H

**Comment by georgemccabe** [comment]
This was implemented a long time ago. Here is an example from pcp_combine_wrapper.py:

            se = sts.StringExtract(self.logger, template,
                                   os.path.basename(f))
            se.parseTemplate()

If se is not set to None, you can use functions like getValidTime to pull time information from that object. See the StringExtact class in string_template_substitution.py

**Comment by bikegeek** [comment]
This should be closed.  We can re-open if necessary.
