### ISSUE TITLE
Replace references to sponsors with use cases names

### ISSUE THREAD

**Issue by TaraJensen** [NCAR/METplus#47]
In an effort to generalize, we need to move away from naming things in METplus by sponsors and rather name it by use case.  

USWRP = qpf
SBU = feature_relative  (other than in tc2cyclone_relative.py)
ExTC = feature or feature_relative

This may be a separate issue but putting it here for now...
Also - we need to figure out how to allow specific references to models in the .conf but not have that embedded in .py code
GFS = remove GFS from GFS_FCST_FILE_TMPL and GFS_ANLY_FILE_TMPL (see met_util.py)

**Comment by georgemccabe** [comment]
This has been resolved. We changed all conf items to start with FCST_ if they correspond to model data and OBS_ if they correspond to observation data. References to specific data sources have also been removed from the code.
