### ISSUE TITLE
Use produtil.run exe() function not batchexe()

### ISSUE THREAD

**Issue by jimfrimel** [NCAR/METplus#48]
Review all code and change to use the exe() function NOT the batchexe() function.

In this process review whether or not we should be passing it through a shell or
revisit how the command arguments are created ...
ie.
cmd = batchexe('sh')['-c',cmd].err2out()
vs.
cmd = batchexe(cmd[0])[cmd[1:]]

Based on feedback from Sam Trahan ...
You need to switch to exe().  Everywhere except WCOSS Cray batch jobs, it has no effect.  On the Cray, it places the executables off of the MAMU nodes.  In general, it is unsafe to run anything on the MAMU nodes on WCOSS Cray.  They have very limited CPU and memory resources, and are shared among many jobs.  Taking down a MAMU node confuses alps and lsf, and can cripple the entire cluster's queueing system, causing jobs to get stuck in the queue until an admin intervenes.

**Comment by georgemccabe** [comment]
All calls to batchexe have been removed or commented out in the code.
