### ISSUE TITLE
Comment out "version" variable from these MET config files in METplus 

### ISSUE THREAD

**Issue by jimfrimel** [NCAR/METplus#55]
TEST this change works.
Remove or comment out the "version" variable in the config files

TCPairsETCConfig
SeriesAnalysisConfig_by_init
SeriesAnalysisConfig_by_lead

Note:
The version variable is no longer required by MET... but if it is present ... it will be checked
against the version of MET that is running (I think).  Removing this from the METplus
instance of the files, removes a nuisance.  That is, when runing METplus against a different 
versions of MET, it is one less thing that has to be changed.

**Comment by georgemccabe** [comment]
As Jim said, this is addressed in the comments of issue #31
