### ISSUE TITLE
Transition from Python 2 to 3

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/METplus#74]

**Comment by jimfrimel** [comment]
The Initial Commit of METplus to Python 3.

See 'develop' branch commit log for details: e4edcde5a3b

The METplus develop branch has been updated and is now python 3.
The develop branch will not run under python 2.

The intent of the INITIAL commit is to make available a port that allows all of
METplus’ current functionally to run so folks can start working with Python 3.
It is expected that more porting will be needed, as issues are discovered, 
and more testing occurs, these will be opened as new issues. 

Technically this port was built and tested with Python 3.6.0 which
was the requirement. 

Here are the notes discussed at the meeting regarding the
python 2 to 3 commit. 

Not sure if everyone has access but it is the document under 
METplus Engineering Meeting Notes folder of the METplus Team Drive  - METplus_python_2_to_3

https://docs.google.com/document/d/1xYXtbdsuXHM80x0-BFeHYJHBepuF-zBRDdWMWRaxRbA

Notes:
The 'develop' branch should be merged into your 'feature_nnn_name' branch
and development should now occur under python 3.
