### ISSUE TITLE
Controlling which data set to run apps such as pcp_combine 

### ISSUE THREAD

**Issue by JohnHalleyGotway** [NCAR/METplus#79]
(1) PcpCombineObs,PcpCombineModel
(2) PcpCombine(Obs),PcpCombine(Model)
(3) PcpCombine
PCPCOMBINE_OPTS = Obs,Model

**Comment by georgemccabe** [comment]
We need to be able to specify if we want to run certain apps (such as pcp_combine and Gempak_to_cf) on observation data or model data. Currently we have 2 classes that can be specified in the process list (see 1 from John's post).

After discussing this with Dan to get the perspective of a user, we concluded that a good way to control this is to have a boolean parameter that is named similarly to the other relevant parameters to determine if you will run or not.

For example,

If PcpCombine is in your process list
    If FCST_PCP_COMBINE_RUN = True
        Run pcp_combine on model data, referring to 
            FCST_PCP_COMBINE_INPUT_DIR, FCST_PCP_COMBINE_INPUT_TEMPLATE, etc.

    If OBS_PCP_COMBINE_RUN = True
        Run pcp_combine on observation data, referring to 
           OBS_PCP_COMBINE_INPUT_DIR, OBS_PCP_COMBINE_INPUT_TEMPLATE, etc.
