### ISSUE TITLE
Update GempakToCF to run stand alone

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/METplus#85]
Wrapper should inherit from ReformatGriddedWrapper

**Comment by georgemccabe** [comment]
It looks like the wrapper should NOT inherit from ReformatGriddedWrapper since RGW uses var list which is not necessary for GempakToCF. You can copy run_at_time() from RGW, put it into GempakToCF wrapper, and remove any mention of var list.

**Comment by jprestop** [comment]
Completed and merged into develop
