### ISSUE TITLE
Remove tc_stat and regrid_data_plane imports from met_util

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/METplus#92]
Currently met_util.py imports the wrappers for tc_stat and regrid_data_plane and calls these applications. met_util.py should only contain utilities that can be used by any application that needs it. This should be refactored to remove the dependency on these wrappers. Could these functions go into the wrappers for each application that they correspond to?

**Comment by bikegeek** [comment]
Created feature_util.py to hold the retrieve_and_regrid() method, since it is used by both extract_tiles_wrapper.py and series_by_lead_wrapper.py.

**Comment by bikegeek** [comment]
feature_92 branch merged into 'develop' branch
