### ISSUE TITLE
Allow wrappers to be run stand alone instead of using master_metplus.py

### ISSUE THREAD

**Issue by georgemccabe** [NCAR/METplus#93]
I wrote a utility function in met_util.py to easily run a wrapper stand alone with command line arguments. To allow a wrapper to be called this way, you can call this utility when name is main (run directly instead of importing), passing in the module (filename) and wrapper name. For example:

`if __name__ == "__main__":
        util.run_stand_alone("pcp_combine_wrapper", "PcpCombine")`

NOTE: The call to util.run_stand_alone() should be on the next line indented. The wiki markup is not formatting it correctly.

I have added this to the following wrappers:
pcp_combine
regrid_data_plane
grid_stat
wavelet_stat
mode

The other wrappers will need to add these files to add this functionality.

**Comment by georgemccabe** [comment]
The following wrappers call util.run_stand_alone when run outside of master METplus (calling grid_stat_wrapper.py with conf args instead of master_metplus.py):

EnsembleStat
ExtractTiles
GridStat
Mode
MTD
PB2NC
PcpCombine
PointStat
RegridDataPlane
SeriesByInit
SeriesByLead
TCMPRPlotter
TcPairs
TcStat

We should add the rest and test that all of the wrappers successfully run this way. Since some use cases have other processes that are run before the wrapper in question, we will have to run the prior steps first before calling the wrapper stand alone.

**Comment by georgemccabe** [comment]
The above comment leads into the discussion that we should have a parm/use_cases/wrapper directory that contains a dir for each wrapper and covers all common uses of that wrapper (i.e. for pcp_combine, conf examples for each mode - add, sum, subtract, derive) that ONLY run that wrapper so there is a clear example of what is needed to set up a given MET tool wrapped in METplus. Issue #231

**Comment by malloryprow** [comment]
Added this for stat_analysis_wrapper.py and make_plots_wrapper.py in feature_226_stat_analysis_cleanup.

**Comment by georgemccabe** [comment]
Currently all of the existing wrappers now call met_util.run_stand_alone with __file__ (the wrapper scripts filename) and the name of the wrapper, i.e. ASCII2NC. The differences between the run_stand_alone function and main in master_metplus.py has grown to be very different, so I extracted the logic from both and reconciled any differences. Now master_metplus.py and run_stand_alone call the same functions to setup, run, and clean up a METplus run. run_stand_alone basically runs METplus but modifies the PROCESS_LIST to only run that wrapper. This ensures that running the wrappers both way will behave the same way.

I testing a handful of use cases by hand and everything seemed to work well. I am running the use case tests to make sure absolutely everything works as intended.

**Comment by georgemccabe** [comment]
The tests passed. Closing this ticket.
